#Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:5.6
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql-password-root
      MYSQL_DATABASE: tuitter_api_server
      MYSQL_USER: admin
      MYSQL_PASSWORD: mysql-password
    volumes:
      - /var/lib/mysql/data
    ports:
      - 3307:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080